"use client";

import { useTenancy } from "@core/providers";

import { Badge } from "@/components/ui/badge";
import { Card, CardDescription, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";

const PLAN_LABEL: Record<string, string> = { free: "Free", pro: "Pro", enterprise: "Enterprise" };

/**
 * Organization identity — name, slug, plan. Read-only: there is no update-org mutation in the
 * console contract yet, so this shows real, live org data rather than a save button that would
 * silently do nothing.
 *
 * The slug is whatever the server persisted. `POST /v1/orgs` generates it with
 * `generate_org_slug()` — a random ten-character string, **not** derived from the name — so an
 * org called "Acme Corporation" gets something like `5pur5t3px8`. That surprises people, who
 * reasonably read a slug as a readable version of the name, so the field says where it comes
 * from instead of presenting it bare and looking broken.
 */
export function TenantSettingsForm() {
  const { org } = useTenancy();

  if (!org) {
    return (
      <Card className="flex flex-col gap-4 p-6">
        <Skeleton className="h-4 w-24" />
        <Skeleton className="h-10 w-full" />
        <Skeleton className="h-10 w-full" />
      </Card>
    );
  }

  return (
    <Card className="flex flex-col gap-4 p-6">
      <div>
        <CardTitle className="text-base">Organization identity</CardTitle>
        <CardDescription className="mt-1">
          Read-only for now. These are the values the organization was created with.
        </CardDescription>
      </div>

      <div className="flex flex-col gap-1.5">
        <Label htmlFor="tenant-name">Name</Label>
        <Input id="tenant-name" value={org.name} disabled readOnly />
      </div>

      <div className="flex flex-col gap-1.5">
        <Label htmlFor="tenant-slug">Slug</Label>
        <Input id="tenant-slug" value={org.slug} disabled readOnly className="font-mono" />
        <p className="text-muted-foreground text-xs">
          Generated by the server when the organization was created. It is not derived from the
          name.
        </p>
      </div>

      <div className="flex items-center justify-between">
        <Label>Plan</Label>
        <Badge variant="mono">{PLAN_LABEL[org.plan] ?? org.plan}</Badge>
      </div>
    </Card>
  );
}
